[tool.ruff]
line-length = 120
target-version = "py311"
include = ["*.py"]
exclude = [
    "build/",
    "dist/",
    "__pycache__/",
    "locale/",
    ".venv/",
]

select = [
    "E",  # Errori PEP8
    "F",  # Flake8 (import inutilizzati, variabili non usate)
    "W",  # Warning PEP8
    "I",  # Import sorting (isort)
    "UP", # Python upgrade (es. usare pathlib, f-string, etc.)
    "RUF" # Regole Ruff specifiche (es. raw strings per regex)
]

ignore = [
    "E501",  # Line too long
]

