[tool.ruff]
line-length = 120
target-version = "py313"
include = ["*.py"]
exclude = [
    "build/",
    "dist/",
    "__pycache__/",
    "locale/",
    ".venv/",
]

select = [
    "E",    # Errori PEP8
    "F",    # Flake8 (import inutili, variabili non usate)
    "W",    # Warning PEP8
    "I",    # Import sorting (isort)
    "UP",   # Upgrade suggeriti per nuove versioni di Python
    "RUF"   # Regole specifiche di Ruff (regex, etc.)
]

ignore = [
    "E501",  # Line too long
]

[tool.ruff.format]
skip = true
