#!/bin/sh
echo "                                                                  "
echo "Glamour Aura FHD OPD skin is now being removed from your receiver."
echo "                                                                  "
