name: GlamourAuraSky-skin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Extract Translations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y automake build-essential gettext python3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Compile Python files
        run: |
          python -m compileall .

      - name: Update .pot file from source
        run: |
          chmod +x locale/updatepot.sh
          ./locale/updatepot.sh

      - name: Compile .po files into .mo
        run: |
          for lang in locale/*.po; do
            langname=$(basename "$lang" .po)
            mkdir -p "locale/$langname/LC_MESSAGES"
            msgfmt "$lang" -o "locale/$langname/LC_MESSAGES/Glam.mo"
          done

